Repository ntohq/education-trail, pull requests merged in 2023-08, with the labels that each got.

#62 Add GitHub actions
  .github/workflows/dotnet.yml
  .github/workflows/react.yml
Labels: front-end, back-end, minor change

#63 Add The GitHub Build Workflow
  .github/workflows/dotnet.yml
  .github/workflows/react.yml
Labels: front-end, back-end, discuss this ASAP, minor change

#69 Documentation for Login Page
  docs/WebPages/login/assets/login_mockup_v0.0.1.jpg
  docs/WebPages/login/components.md
  docs/WebPages/login/integrations.md
  docs/WebPages/login/page.md
Labels: documentation

#70 ISSUE 41 - Added NavigiationFooter
  src/EducationTrail/ClientApp/src/AppRoutes.js
  src/EducationTrail/ClientApp/src/assets/images/coffee-bear.png
  src/EducationTrail/ClientApp/src/components/NavFooter.js
  src/EducationTrail/ClientApp/src/components/NavMenu.js
  src/EducationTrail/ClientApp/src/custom.css
  src/EducationTrail/ClientApp/src/layouts/HomeLayout.js
  src/EducationTrail/ClientApp/src/layouts/Layout.js
  src/EducationTrail/ClientApp/src/pages/Signup.js
  src/EducationTrail/ClientApp/src/pages/product/Hub.js
  src/EducationTrail/ClientApp/tailwind.config.js
Labels: front-end, minor change
